name: Sandbox Workflow

on:
  workflow_dispatch:
  push:

jobs:
  sandbox:
    name: sandbox
    runs-on: ubuntu-latest
    
    steps:
      - name: Add env
        run: echo $(grep WORKING_DIR ./.secrets.sample | cut -d '=' -f 2) >> $GITHUB_ENV
        
      - name: Try here
        run: echo $WORKING_DIR
