name: Sandbox Workflow

on:
  workflow_dispatch:
  push:

jobs:
  sandbox:
    name: sandbox
    runs-on: ubuntu-latest
    
    steps:
      - name: Prepare
        run: echo 'WORKING_DIR=/work' > ./.secrets.sample
    
      - name: Add env
        run: export WORKING_DIR="$(grep WORKING_DIR ./.secrets.sample | cut -d '=' -f 2)"
        
      - name: Try here
        run: echo $WORKING_DIR
