name: On Release Created Sample

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  on_release_created_sample:
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: echo "On Release Created Sample"

      - name:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: echo "if test"
