name: Richcat PyPI Workflow Debug

on:
  push:

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Upload to PyPI
        id: upload
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Uploaded."

      - name: Create release
        # if: steps.upload.conclusion == 'success'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
