name: Richcat PyPI Workflow Debug

on:
  push:

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: |
          echo "${GITHUB_REF#refs/tags/}"
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Upload to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: echo "Uploaded."

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_tag.outputs.version }}
          release_name: Release v${{ steps.create_tag.outputs.version }}
          draft: false
          prerelease: false
