name: Richcat PyPI Workflow Debug

on:
  push:

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest

    outputs:
      richcat_version: ${{ steps.get_version.outputs.version }}
      uploaded: ${{ steps.upload.outputs.uploaded }}

    steps:
      - name: Get version
        id: get_version
        env:
          VERSION: ${GITHUB_REF#refs/tags/}
        run: |
          echo "$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Upload to PyPI
        id: upload
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Uploaded."
          echo "::set-output name=uploaded::0"

  create_release:
    runs-on: ubuntu-latest
    needs: upload_to_pypi
    if: ${{ needs.upload_to_pypi.outputs.uploaded == 0 }}

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RICHCAT_VERSION: ${{ needs.upload_to_pypi.outputs.richcat_version }}
        with:
          tag_name: v$RICHCAT_VERSION
          release_name: Release v$RICHCAT_VERSION
          draft: false
          prerelease: false
