name: Richcat PyPI Workflow Debug

on:
  push:

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest

    outputs:
      richcat_version: ${{ steps.get_version.outputs.version }}
      uploaded: ${{ steps.upload.outputs.uploaded }}

    steps:
      - name: Get version
        id: get_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Upload to PyPI
        id: upload
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Uploaded."
          echo "::set-output name=uploaded::0"

  create_release:
    runs-on: ubuntu-latest
    needs: upload_to_pypi
    # if: ${{ needs.upload_to_pypi.outputs.uploaded == 0 }}

    steps:
      - name: if result
        run: echo __${{ needs.upload_to_pypi.outputs.uploaded }}__
      # - name: Create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ needs.upload_to_pypi.outputs.richcat_version }}
      #     release_name: Release v${{ needs.upload_to_pypi.outputs.richcat_version }}
      #     draft: false
      #     prerelease: false
